# Generated by Django 4.1.3 on 2022-11-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование товара')),
                ('description', models.TextField(max_length=500, verbose_name='Описание товара')),
                ('price', models.IntegerField(default=0, verbose_name='Цена товара')),
            ],
        ),
    ]
